#!/bin/sh

syscallTableNumber=$(sudo grep sys_call_table /boot/System.map-$(uname -r) | cut -f 1 -d " ")
echo "// This is a file generated by 'getEnvironmentSpecificOptions.sh'. DO NOT EDIT"
echo "#define SYSCALL_TABLE ((void *) 0x$syscallTableNumber)"

